server:
  port: 8081
spring:
  #autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    #url: jdbc:oracle:thin:@localhost:1521:ORCLPDB1
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    driver-class-name: oracle.jdbc.OracleDriver
    username: EMPLOYEE
    password: dudkrish1A
    jpa:
      show-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
          format_sql: true
      database-platform: org.hibernate.dialect.Oracle12cDialect
  sql:
    init:
      continue-on-error: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE   # Log query parameters
    #org.hibernate.orm.jdbc.extract: TRACE  # Log extracted results

#brew install redis
#redis-server --version
#brew services start redis
#redis-cli